ALTER TABLE servers ADD COLUMN http_url TEXT NOT NULL DEFAULT '';
ALTER TABLE servers ADD COLUMN http_method TEXT NOT NULL DEFAULT 'GET';
ALTER TABLE servers ADD COLUMN http_expected_status TEXT NOT NULL DEFAULT '200-399';
ALTER TABLE servers ADD COLUMN tcp_host TEXT NOT NULL DEFAULT '';
ALTER TABLE servers ADD COLUMN tcp_port INTEGER NOT NULL DEFAULT 0;
ALTER TABLE servers ADD COLUMN probe_timeout_ms INTEGER NOT NULL DEFAULT 10000;
ALTER TABLE servers ADD COLUMN recovery_action TEXT NOT NULL DEFAULT 'reboot';

CREATE TABLE IF NOT EXISTS check_results (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  server_id TEXT NOT NULL,
  ok INTEGER NOT NULL,
  latency_ms INTEGER NOT NULL DEFAULT 0,
  status_value TEXT NOT NULL DEFAULT '',
  error TEXT NOT NULL DEFAULT '',
  created_at INTEGER NOT NULL
);

UPDATE settings SET value = '3' WHERE key = 'suspect_threshold' AND value = '2';
